import java.text.SimpleDateFormat;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author INFINIX
 */
public class frame1 extends javax.swing.JInternalFrame {
    private DefaultListModel<String> listModel;
    private DefaultListModel<String> detailModel;
    private int nomor = 1;
    /**
     * Creates new form frame1
     */
    public frame1() {
        initComponents();
        listModel = new DefaultListModel<>();
        detailModel = new DefaultListModel<>();
        lList.setModel(listModel);
        lList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
        public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
            lListValueChanged(evt);
            }  
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lbJudul = new javax.swing.JLabel();
        lbMatkul = new javax.swing.JLabel();
        lbDeadline = new javax.swing.JLabel();
        lbDetail = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDetail = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfMatkul = new javax.swing.JTextField();
        btClear = new javax.swing.JButton();
        btSimpan = new javax.swing.JButton();
        jDate = new com.toedter.calendar.JDateChooser();
        lbBg = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbJudul2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lList = new javax.swing.JList<>();
        lbDetail2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taDetail2 = new javax.swing.JTextArea();
        btnBersih = new javax.swing.JButton();
        lbBg1 = new javax.swing.JLabel();

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbJudul.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lbJudul.setText("Tambah Tugas Baru");
        jPanel2.add(lbJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        lbMatkul.setText("Nama Mata Kuliah");
        jPanel2.add(lbMatkul, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        lbDeadline.setText("Deadline Tugas");
        jPanel2.add(lbDeadline, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        lbDetail.setText("Detail Tugas");
        jPanel2.add(lbDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        taDetail.setColumns(20);
        taDetail.setRows(5);
        jScrollPane1.setViewportView(taDetail);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 350, -1));

        jLabel5.setText(":");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 10, -1));

        jLabel7.setText(":");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 10, -1));

        jLabel8.setText(":");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 10, -1));
        jPanel2.add(tfMatkul, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 220, -1));

        btClear.setText("Clear");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });
        jPanel2.add(btClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));

        btSimpan.setText("Simpan");
        btSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimpanActionPerformed(evt);
            }
        });
        jPanel2.add(btSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, -1, -1));
        jPanel2.add(jDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 220, -1));

        lbBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blue.png"))); // NOI18N
        jPanel2.add(lbBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("Tambah Tugas", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbJudul2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lbJudul2.setText("Daftar Tugas");
        jPanel3.add(lbJudul2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        lList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lList);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 180, 230));

        lbDetail2.setText("Detail Tugas");
        jPanel3.add(lbDetail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        taDetail2.setColumns(20);
        taDetail2.setRows(5);
        jScrollPane3.setViewportView(taDetail2);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 130, 240, 180));

        btnBersih.setText("Bersihkan");
        btnBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBersihActionPerformed(evt);
            }
        });
        jPanel3.add(btnBersih, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, -1, -1));

        lbBg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blue.png"))); // NOI18N
        jPanel3.add(lbBg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("Daftar Tugas", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpanActionPerformed
        // TODO add your handling code here:
        String matkul = tfMatkul.getText();
        java.util.Date deadlineDate = jDate.getDate();
        String detail = taDetail.getText();

        if (matkul.isEmpty() || deadlineDate == null || detail.isEmpty()) {
            JOptionPane.showMessageDialog(null, 
                    "Lengkapi data terlebih dahulu!!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String deadline = dateFormat.format(deadlineDate);

            // Simpan data jika semua input telah diisi
            String namaDanTugas = nomor + ". " + matkul + " (dl: " + deadline + ")";
            listModel.addElement(namaDanTugas);
            detailModel.addElement(detail);
            nomor++;
        }
    }//GEN-LAST:event_btSimpanActionPerformed

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        // TODO add your handling code here:                                         
        // TODO add your handling code here:
        tfMatkul.setText("");
        jDate.setDate(null);
        taDetail.setText("");

    }//GEN-LAST:event_btClearActionPerformed

    private void lListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lListValueChanged
        // TODO add your handling code here:
        if (!evt.getValueIsAdjusting()) {
            int selectedIndex = lList.getSelectedIndex();
            if (selectedIndex != -1) {
                String detail = detailModel.getElementAt(selectedIndex); // Ambil detail sesuai dengan indeks
                taDetail2.setText(detail);
            }
        }
    }//GEN-LAST:event_lListValueChanged

    private void btnBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBersihActionPerformed
        // TODO add your handling code here:
        int[] selectedIndices = lList.getSelectedIndices();
    
        if (selectedIndices.length > 0) {
            for (int i = selectedIndices.length - 1; i >= 0; i--) {
                listModel.removeElementAt(selectedIndices[i]);
                detailModel.removeElementAt(selectedIndices[i]);
            }

            for (int i = 0; i < listModel.getSize(); i++) {
                String existingItem = listModel.getElementAt(i);
                String[] parts = existingItem.split("\\. ");
                int existingNomor = i + 1;
                String newItem = existingNomor + ". " + parts[1];
                listModel.setElementAt(newItem, i);
            }
            taDetail2.setText("");
            nomor = 1;
        } else {
            listModel.removeAllElements();
            detailModel.removeAllElements();
            taDetail2.setText("");
            nomor = 1;
        }
    }//GEN-LAST:event_btnBersihActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClear;
    private javax.swing.JButton btSimpan;
    private javax.swing.JButton btnBersih;
    private com.toedter.calendar.JDateChooser jDate;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> lList;
    private javax.swing.JLabel lbBg;
    private javax.swing.JLabel lbBg1;
    private javax.swing.JLabel lbDeadline;
    private javax.swing.JLabel lbDetail;
    private javax.swing.JLabel lbDetail2;
    private javax.swing.JLabel lbJudul;
    private javax.swing.JLabel lbJudul2;
    private javax.swing.JLabel lbMatkul;
    private javax.swing.JTextArea taDetail;
    private javax.swing.JTextArea taDetail2;
    private javax.swing.JTextField tfMatkul;
    // End of variables declaration//GEN-END:variables
}